In [13]:
import numpy as np
from scipy import integrate, linalg, optimize

A = np.zeros((3,3), dtype = np.float128)
B = np.zeros((3,3), dtype = np.float128)
A_eval = np.zeros((3), dtype = np.float128)
A_evec = np.zeros((3,3), dtype = np.float128)
B_eval = np.zeros((3), dtype = np.float128)
B_evec = np.zeros((3,3), dtype = np.float128)

print(type(A_eval[0]))

for i in range(3):
    for j in range(3):
        A[i,j] = i**j
        B[i,j] = i + j

print("A\n",A)
print("B\n",B)

A_eval, A_evec = linalg.eig(A)
B_eval, B_evec = linalg.eig(B)

print(type(A_eval[0]))

<class 'numpy.float128'>
A
 [[1. 0. 0.]
 [1. 1. 1.]
 [1. 2. 4.]]
B
 [[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
<class 'numpy.complex128'>
