In [3]:
import numpy as np

# a = np.ones(100)
# b = np.fft.fft(a, 100)
# print(b)

def func(x, *args):
    fun = a * x + b
    return fun

def funcational(func, x, *args):
    a = func(x, *args)
    return a

In [4]:
a = np.array([3,-5,1,-9,0,6,-9,2,8])
b = a**2
print(a)
print(b)
print()

index = np.argsort(a)
print(index + 1)

print()
a = a[index][::-1]
b = b[index][::-1]
print(a)
print(b)

[ 3 -5  1 -9  0  6 -9  2  8]
[ 9 25  1 81  0 36 81  4 64]

[4 7 2 5 3 8 1 6 9]

[ 8  6  3  2  1  0 -5 -9 -9]
[64 36  9  4  1  0 25 81 81]
